"""Generate the S1 run tables from logs. Script-generated only — never hand-assembled.

§9 standing obligation: "Every figure generated by script from logged results into `paper/figures/`.
Never hand-assembled. Once one figure is hand-made the habit is gone." Latency figures reported during
S1-b were computed with ad-hoc shell one-liners, which is the same failure in a different costume. This
module is the replacement: every rate, count and verdict below is derived from files on disk.

Emits:
  paper/figures/s1_run_summary.md     per-run: actions, levels, rate, operating point
  paper/figures/s1_calls_per_turn.md  model calls per game turn, from D6 request logs
  logs/s1_run_summary.json            machine-readable, for the Day-7 ranking

Run:  .venv/bin/python agent/harness/make_run_tables.py
"""

from __future__ import annotations

import collections
import datetime as _dt
import glob
import json
import os
import re
import statistics
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RUNS = REPO / "logs" / "runs"
FIGURES = REPO / "paper" / "figures"


def run_started_at(run_dir: Path) -> _dt.datetime | None:
    m = re.match(r"(\d{8})_(\d{6})_", run_dir.name)
    if not m:
        return None
    return _dt.datetime.strptime(m.group(1) + m.group(2), "%Y%m%d%H%M%S")


def newest_mtime(paths) -> float | None:
    ts = [os.path.getmtime(p) for p in paths if os.path.exists(p)]
    return max(ts) if ts else None


def summarise_run(run_dir: Path) -> dict | None:
    events = sorted(glob.glob(str(run_dir / "artifacts" / "*_events.jsonl")))
    if not events:
        return None
    started = run_started_at(run_dir)
    passes, total_actions, max_level, levels_done = [], 0, 0, 0
    for f in events:
        try:
            rows = [json.loads(l) for l in open(f)]
        except Exception:  # noqa: BLE001
            continue
        if not rows:
            continue
        actions = len(rows) - 1                      # row 0 is the initial RESET frame
        last = rows[-1]
        lvl = int(last.get("level") or 0)
        sc = int(last.get("score") or 0)
        total_actions += actions
        max_level = max(max_level, lvl)
        levels_done = max(levels_done, sc)
        passes.append({"pass": Path(f).name.split("_events")[0], "actions": actions,
                       "level": lvl, "score": sc, "state": last.get("state")})

    # Wall-clock: run-dir name gives the start; newest artifact mtime gives the last activity.
    end_ts = newest_mtime(events)
    elapsed_s = (end_ts - started.timestamp()) if (started and end_ts) else None
    rate = (elapsed_s / (total_actions / len(passes))) if (elapsed_s and total_actions) else None

    return {"run": run_dir.name, "passes": len(passes), "total_actions": total_actions,
            "levels_completed": levels_done, "max_level_reached": max_level,
            "elapsed_s": round(elapsed_s) if elapsed_s else None,
            "seconds_per_action_per_pass": round(rate, 1) if rate else None,
            "detail": passes}


def calls_per_turn(run_dir: Path) -> collections.Counter:
    """Model calls per game turn, counted by where `request_index_within_turn` resets to 1."""
    c: collections.Counter = collections.Counter()
    for f in glob.glob(str(run_dir / "*requests.jsonl")):
        cur = 0
        for line in open(f):
            try:
                i = json.loads(line).get("request_index_within_turn") or 0
            except Exception:  # noqa: BLE001
                continue
            if i == 1:
                if cur:
                    c[cur] += 1
                cur = 1
            else:
                cur = max(cur, i)
        if cur:
            c[cur] += 1
    return c


def main() -> None:
    FIGURES.mkdir(parents=True, exist_ok=True)
    runs = sorted([p for p in RUNS.iterdir() if p.is_dir()]) if RUNS.exists() else []
    summaries = [s for s in (summarise_run(r) for r in runs) if s]

    lines = ["# S1 run summary", "",
             "*Generated by `agent/harness/make_run_tables.py` from `logs/runs/`. Do not edit by hand.*",
             "",
             "| run | passes | actions | levels done | max level | elapsed | s/action/pass |",
             "|---|---:|---:|---:|---:|---:|---:|"]
    for s in summaries:
        el = f"{s['elapsed_s']//60} min" if s["elapsed_s"] else "—"
        rate = s["seconds_per_action_per_pass"] or "—"
        lines.append(f"| `{s['run']}` | {s['passes']} | {s['total_actions']} | "
                     f"**{s['levels_completed']}** | {s['max_level_reached']} | {el} | {rate} |")
    lines += ["", "**levels done** counts completed levels (the events' `score` field), which is the",
              "S1-b hard-exit criterion — not the leaderboard score."]
    (FIGURES / "s1_run_summary.md").write_text("\n".join(lines) + "\n")

    lines = ["# Model calls per game turn", "",
             "*Generated by `agent/harness/make_run_tables.py` from D6 `requests.jsonl`. Do not edit by hand.*",
             "",
             "Counted by where `request_index_within_turn` resets to 1. The reference operating point is",
             "`analyzer.tool_steps: 0` = **unlimited**; runs driven directly at the module (bypassing the",
             "Makefile) instead got the code default of 12.", "",
             "| run | turns | mean calls/turn | max | distribution |", "|---|---:|---:|---:|---|"]
    for r in runs:
        c = calls_per_turn(r)
        if not c:
            continue
        n = sum(c.values())
        mean = sum(k * v for k, v in c.items()) / n
        dist = ", ".join(f"{k}:{v}" for k, v in sorted(c.items()))
        lines.append(f"| `{r.name}` | {n} | {mean:.2f} | {max(c)} | {dist} |")
    (FIGURES / "s1_calls_per_turn.md").write_text("\n".join(lines) + "\n")

    (REPO / "logs" / "s1_run_summary.json").write_text(json.dumps(summaries, indent=2) + "\n")
    print(f"wrote {FIGURES/'s1_run_summary.md'}")
    print(f"wrote {FIGURES/'s1_calls_per_turn.md'}")
    print(f"wrote {REPO/'logs'/'s1_run_summary.json'}")
    for s in summaries:
        print(f"  {s['run']}: {s['total_actions']} actions, {s['levels_completed']} levels, "
              f"{s['seconds_per_action_per_pass']}s/action/pass")


if __name__ == "__main__":
    main()
