"""Generate the S1 run tables from logs. Script-generated only — never hand-assembled.

§9 standing obligation: "Every figure generated by script from logged results into `paper/figures/`.
Never hand-assembled. Once one figure is hand-made the habit is gone." Latency figures reported during
S1-b were computed with ad-hoc shell one-liners, which is the same failure in a different costume. This
module is the replacement: every rate, count and verdict below is derived from files on disk.

Emits:
  paper/figures/s1_run_summary.md     per-run: actions, levels, rate, operating point
  paper/figures/s1_calls_per_turn.md  model calls per game turn, from D6 request logs
  logs/s1_run_summary.json            machine-readable, for the Day-7 ranking

Run:  .venv/bin/python agent/harness/make_run_tables.py
"""

from __future__ import annotations

import collections
import datetime as _dt
import glob
import json
import os
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RUNS = REPO / "logs" / "runs"
FIGURES = REPO / "paper" / "figures"


def run_started_at(run_dir: Path) -> _dt.datetime | None:
    m = re.match(r"(\d{8})_(\d{6})_", run_dir.name)
    if not m:
        return None
    return _dt.datetime.strptime(m.group(1) + m.group(2), "%Y%m%d%H%M%S")


def newest_mtime(paths) -> float | None:
    ts = [os.path.getmtime(p) for p in paths if os.path.exists(p)]
    return max(ts) if ts else None


# A run is tabulated ONLY on an explicit terminal marker. Artifact quiescence was tried and is
# UNSOUND: measured generation durations on this hardware reach 306 s with 14/40 exceeding 180 s, so a
# live run routinely goes quiet for longer than any plausible timeout. A heuristic that cannot separate
# "killed" from "mid-inference" would publish a still-growing run as stable evidence.
FINALIZED_MARKER = "SNAPSHOT_FINALIZED"


def run_status(run_dir: Path) -> str | None:
    """`closed` | `truncated` | None (excluded).

    `closed`    — benchmark.json closed cleanly: end_time set and no game_run left `playing`.
    `truncated` — an operator dropped a FINALIZED_MARKER file, asserting the process is dead and the
                  artifacts will not change. Killed runs need this; nothing infers it.
    None        — neither; excluded from every table.
    """
    bj = run_dir / "benchmark.json"
    if bj.exists():
        try:
            b = json.loads(bj.read_text())
        except Exception:  # noqa: BLE001
            b = None
        if b and b.get("end_time") is not None and all(
                (gr.get("state") not in (None, "playing")) for gr in (b.get("game_runs") or [])):
            return "closed"
    if (run_dir / FINALIZED_MARKER).exists():
        return "truncated"
    return None


def summarise_run(run_dir: Path) -> dict | None:
    events = sorted(glob.glob(str(run_dir / "artifacts" / "*_events.jsonl")))
    if not events:
        return None
    started = run_started_at(run_dir)
    passes, total_actions, max_level, levels_done = [], 0, 0, 0
    for f in events:
        try:
            rows = [json.loads(l) for l in open(f)]
        except Exception:  # noqa: BLE001
            continue
        if not rows:
            continue
        # COUNT ONLY EXECUTED GAME ACTIONS. The event stream interleaves `initial`, `analysis` and
        # `action` records; `analysis` rows are reasoning snapshots that consumed no game action.
        # `len(rows) - 1` conflates them and inflated every earlier figure — the three ft09 runs contain
        # ZERO `action` records yet were reported as 24, 8 and 20 actions.
        actions = sum(1 for r in rows if r.get("type") == "action")
        last = rows[-1]
        lvl = int(last.get("level") or 0)
        sc = int(last.get("score") or 0)
        total_actions += actions
        max_level = max(max_level, lvl)
        levels_done = max(levels_done, sc)
        passes.append({"pass": Path(f).name.split("_events")[0], "actions": actions,
                       "level": lvl, "score": sc, "state": last.get("state")})

    # Wall-clock: run-dir name gives the start; newest artifact mtime gives the last activity.
    end_ts = newest_mtime(events)
    elapsed_s = (end_ts - started.timestamp()) if (started and end_ts) else None
    rate = (elapsed_s / (total_actions / len(passes))) if (elapsed_s and total_actions) else None

    return {"run": run_dir.name, "passes": len(passes), "total_actions": total_actions,
            "levels_completed": levels_done, "max_level_reached": max_level,
            "elapsed_s": round(elapsed_s) if elapsed_s else None,
            "seconds_per_action_per_pass": round(rate, 1) if rate else None,
            "detail": passes}


def calls_per_turn(run_dir: Path) -> collections.Counter:
    """Model calls per game turn, counted by where `request_index_within_turn` resets to 1."""
    c: collections.Counter = collections.Counter()
    for f in glob.glob(str(run_dir / "*requests.jsonl")):
        cur = 0
        for line in open(f):
            try:
                rec = json.loads(line)
            except Exception:  # noqa: BLE001
                continue
            # D6 writes a `request` AND a `response` record sharing the same index. Counting both makes
            # every response with index 1 look like a new turn, roughly doubling the turn count and
            # deflating the mean.
            if rec.get("event") != "request":
                continue
            i = rec.get("request_index_within_turn") or 0
            if i == 1:
                if cur:
                    c[cur] += 1
                cur = 1
            else:
                cur = max(cur, i)
        if cur:
            c[cur] += 1
    return c


def main() -> None:
    FIGURES.mkdir(parents=True, exist_ok=True)
    all_runs = sorted([p for p in RUNS.iterdir() if p.is_dir()]) if RUNS.exists() else []
    statuses = {r: run_status(r) for r in all_runs}
    runs = [r for r in all_runs if statuses[r] is not None]
    skipped = [r.name for r in all_runs if statuses[r] is None]
    summaries = []
    for r in runs:
        summ = summarise_run(r)
        if summ:
            summ["status"] = statuses[r]
            summaries.append(summ)
    if skipped:
        print("SKIPPED (no terminal marker; drop a SNAPSHOT_FINALIZED file to include): "
              + ", ".join(skipped))

    lines = ["# S1 run summary", "",
             "*Generated by `agent/harness/make_run_tables.py` from `logs/runs/`. Do not edit by hand.*",
             "",
             "| run | status | passes | actions | levels done | max level | elapsed | s/action/pass |",
             "|---|---|---:|---:|---:|---:|---:|---:|"]
    for s in summaries:
        el = f"{s['elapsed_s']//60} min" if s["elapsed_s"] else "—"
        rate = s["seconds_per_action_per_pass"] or "—"
        lines.append(f"| `{s['run']}` | {s['status']} | {s['passes']} | {s['total_actions']} | "
                     f"**{s['levels_completed']}** | {s['max_level_reached']} | {el} | {rate} |")
    lines += ["", "**actions** counts only `type == \"action\"` event records — executed game actions.",
              "`analysis` records are reasoning snapshots and consume no game action.",
              "**levels done** counts completed levels, the S1-b hard-exit criterion — not a leaderboard score.",
              "", "**status**: `closed` = benchmark.json closed cleanly. `truncated` = an operator",
              "asserted the process is dead via a `SNAPSHOT_FINALIZED` marker. Runs with neither are",
              "excluded. Quiescence is NOT used: measured generation durations reach 306 s here, so a",
              "live run routinely goes quiet longer than any timeout could safely treat as stopped."]
    (FIGURES / "s1_run_summary.md").write_text("\n".join(lines) + "\n")

    lines = ["# Model calls per game turn", "",
             "*Generated by `agent/harness/make_run_tables.py` from D6 `requests.jsonl`. Do not edit by hand.*",
             "",
             "Counted by where `request_index_within_turn` resets to 1. The reference operating point is",
             "`analyzer.tool_steps: 0` = **unlimited**; runs driven directly at the module (bypassing the",
             "Makefile) instead got the code default of 12.", "",
             "| run | turns | mean calls/turn | max | distribution |", "|---|---:|---:|---:|---|"]
    for r in runs:
        c = calls_per_turn(r)
        if not c:
            continue
        n = sum(c.values())
        mean = sum(k * v for k, v in c.items()) / n
        dist = ", ".join(f"{k}:{v}" for k, v in sorted(c.items()))
        lines.append(f"| `{r.name}` | {n} | {mean:.2f} | {max(c)} | {dist} |")
    (FIGURES / "s1_calls_per_turn.md").write_text("\n".join(lines) + "\n")

    (REPO / "logs" / "s1_run_summary.json").write_text(json.dumps(summaries, indent=2) + "\n")
    print(f"wrote {FIGURES/'s1_run_summary.md'}")
    print(f"wrote {FIGURES/'s1_calls_per_turn.md'}")
    print(f"wrote {REPO/'logs'/'s1_run_summary.json'}")
    for s in summaries:
        print(f"  {s['run']}: {s['total_actions']} actions, {s['levels_completed']} levels, "
              f"{s['seconds_per_action_per_pass']}s/action/pass")


if __name__ == "__main__":
    main()
