#!/usr/bin/env python3
"""What an encoder-side frame cap actually discards.

`gate_manifest.yaml -> s2.frame_cap` proposes `encoder_frames_max: 8` on the rationale that it
"covers 92.5% of observations". That figure is correct and it is also the denominator that makes
the cap look nearly free: 92.47% of OBSERVATIONS survive untouched, but 26.71% of all GRIDS are
discarded, and the loss is concentrated in a handful of games rather than spread evenly.

This script regenerates every number the manifest's `cost_restated_2026-07-29` block asserts, so
those numbers are reproduced from the log rather than transcribed into a pre-registration by hand
(CLAUDE.md: "figures are generated by script from logs, never hand-assembled").

    python agent/harness/s2_frame_cap_cost.py            # print the tables
    python agent/harness/s2_frame_cap_cost.py --verify   # compare against the manifest; exit 1 on drift

Input: logs/s2_corpus_census.json, `framelen` per game -- {frame_count: n_observations}.
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
CENSUS = ROOT / "logs" / "s2_corpus_census.json"
MANIFEST = ROOT / "gate_manifest.yaml"

# The caps the manifest tabulates. Kept here rather than read from the manifest so `--verify`
# compares two independent derivations instead of checking the manifest against itself.
CAPS = (4, 8, 16, 32)

# Games the manifest calls out individually, and the cap it calls them out at.
CONCENTRATION_CAP = 8
CALLED_OUT = ("tu93", "sb26", "g50t", "bp35")

TOL = 5e-5  # the manifest stores 5 significant decimals


def load_framelens() -> dict[str, dict[int, int]]:
    census = json.loads(CENSUS.read_text())
    out = {}
    for game, rec in census.items():
        fl = rec.get("framelen") or {}
        if fl:
            out[game] = {int(k): int(n) for k, n in fl.items()}
    return out


def totals(fl: dict[int, int]) -> tuple[int, int]:
    """(observations, grids) -- an observation of length k contributes k grids."""
    return sum(fl.values()), sum(k * n for k, n in fl.items())


def cap_cost(fl: dict[int, int], cap: int) -> tuple[float, float]:
    """(share of observations untouched, share of grids dropped) at this cap."""
    obs, grids = totals(fl)
    if not obs or not grids:
        return 1.0, 0.0
    truncated = sum(n for k, n in fl.items() if k > cap)
    retained = sum(min(k, cap) * n for k, n in fl.items())
    return 1.0 - truncated / obs, 1.0 - retained / grids


def pooled(per_game: dict[str, dict[int, int]]) -> dict[int, int]:
    agg: collections.Counter[int] = collections.Counter()
    for fl in per_game.values():
        agg.update(fl)
    return dict(agg)


def report(per_game: dict[str, dict[int, int]]) -> dict:
    agg = pooled(per_game)
    obs, grids = totals(agg)

    basis = {
        "observations": obs,
        "grids": grids,
        "mean": grids / obs,
        "max": max(agg),
        "single_frame_share": agg.get(1, 0) / obs,
    }
    by_cap = {cap: cap_cost(agg, cap) for cap in CAPS}

    concentration = {}
    untouched = 0
    for game, fl in per_game.items():
        keep, drop = cap_cost(fl, CONCENTRATION_CAP)
        concentration[game] = (1.0 - keep, drop)  # (observations truncated, grids dropped)
        if max(fl) <= CONCENTRATION_CAP:
            untouched += 1

    return {
        "basis": basis,
        "by_cap": by_cap,
        "concentration": concentration,
        "untouched_games": untouched,
    }


def render(r: dict) -> None:
    b = r["basis"]
    print(
        f"basis: {b['observations']:,} observations  {b['grids']:,} grids  "
        f"mean {b['mean']:.3f}  max {b['max']}  single-frame {b['single_frame_share']:.3%}"
    )
    print("\ncap   observations untouched   grids dropped")
    for cap, (keep, drop) in sorted(r["by_cap"].items()):
        print(f"{cap:3d}   {keep:19.3%}   {drop:13.3%}")

    print(f"\nper game at cap {CONCENTRATION_CAP}, worst grid loss first:")
    print("game    obs truncated   grids dropped")
    ranked = sorted(r["concentration"].items(), key=lambda kv: -kv[1][1])
    for game, (otr, gdr) in ranked:
        flag = "   <-- manifest calls this out" if game in CALLED_OUT else ""
        print(f"{game:6s}  {otr:12.2%}   {gdr:12.2%}{flag}")
    print(f"\nuntouched games (max framelen <= {CONCENTRATION_CAP}): {r['untouched_games']}")


def verify(r: dict) -> int:
    """Compare against gate_manifest.yaml -> s2.frame_cap.cost_restated_2026-07-29."""
    try:
        import yaml
    except ImportError:
        print("verify needs PyYAML", file=sys.stderr)
        return 2

    block = yaml.safe_load(MANIFEST.read_text())["s2"]["frame_cap"]["cost_restated_2026-07-29"]
    drift: list[str] = []

    def cmp(label: str, got: float, want: float) -> None:
        if abs(got - want) > TOL:
            drift.append(f"{label}: script {got:.5f} != manifest {want:.5f}")

    for cap, (keep, drop) in r["by_cap"].items():
        rec = block["by_cap"].get(f"cap_{cap}")
        if rec is None:
            drift.append(f"cap_{cap}: absent from the manifest")
            continue
        cmp(f"cap_{cap}.observations_untouched", keep, rec["observations_untouched"])
        cmp(f"cap_{cap}.grids_dropped", drop, rec["grids_dropped"])

    conc = block["concentration_at_cap_8"]
    for game in CALLED_OUT:
        otr, gdr = r["concentration"][game]
        cmp(f"{game}.observations_truncated", otr, conc[game]["observations_truncated"])
        cmp(f"{game}.grids_dropped", gdr, conc[game]["grids_dropped"])

    if conc["untouched_games"] != r["untouched_games"]:
        drift.append(
            f"untouched_games: script {r['untouched_games']} != manifest {conc['untouched_games']}"
        )

    if drift:
        print("DRIFT — the manifest does not match the census:", file=sys.stderr)
        for d in drift:
            print(f"  {d}", file=sys.stderr)
        return 1

    print(f"OK — {len(r['by_cap'])} caps and {len(CALLED_OUT)} called-out games match the manifest")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--verify", action="store_true", help="compare against the manifest; exit 1 on drift")
    args = ap.parse_args()

    if not CENSUS.exists():
        print(f"missing {CENSUS}; run agent/harness/s2_corpus_census.py first", file=sys.stderr)
        return 2

    r = report(load_framelens())
    if args.verify:
        return verify(r)
    render(r)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
